version: '3.8'

services:
  glossary:
    build: ./glossary_service
    ports:
      - "8080:8080"  # Flask frontend/API
      - "50051:50051" # gRPC
    volumes:
      - ./glossary_service:/usr/src/app
      - ./frontend:/usr/src/app/frontend
    command: python server.py
