# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: glossary.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'glossary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eglossary.proto\x12\x08glossary\"d\n\x04Term\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04term\x18\x02 \x01(\t\x12\x12\n\ndefinition\x18\x03 \x01(\t\x12\x14\n\x0csource_links\x18\x04 \x03(\t\x12\x18\n\x10related_term_ids\x18\x05 \x03(\t\"!\n\x0eGetTermRequest\x12\x0f\n\x07term_id\x18\x01 \x01(\t\"b\n\x0e\x41\x64\x64TermRequest\x12\x0c\n\x04term\x18\x01 \x01(\t\x12\x12\n\ndefinition\x18\x02 \x01(\t\x12\x14\n\x0csource_links\x18\x03 \x03(\t\x12\x18\n\x10related_term_ids\x18\x04 \x03(\t\"\x12\n\x10ListTermsRequest\")\n\x08TermList\x12\x1d\n\x05terms\x18\x01 \x03(\x0b\x32\x0e.glossary.Term2\xb8\x01\n\x0fGlossaryService\x12\x33\n\x07GetTerm\x12\x18.glossary.GetTermRequest\x1a\x0e.glossary.Term\x12\x33\n\x07\x41\x64\x64Term\x12\x18.glossary.AddTermRequest\x1a\x0e.glossary.Term\x12;\n\tListTerms\x12\x1a.glossary.ListTermsRequest\x1a\x12.glossary.TermListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'glossary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TERM']._serialized_start=28
  _globals['_TERM']._serialized_end=128
  _globals['_GETTERMREQUEST']._serialized_start=130
  _globals['_GETTERMREQUEST']._serialized_end=163
  _globals['_ADDTERMREQUEST']._serialized_start=165
  _globals['_ADDTERMREQUEST']._serialized_end=263
  _globals['_LISTTERMSREQUEST']._serialized_start=265
  _globals['_LISTTERMSREQUEST']._serialized_end=283
  _globals['_TERMLIST']._serialized_start=285
  _globals['_TERMLIST']._serialized_end=326
  _globals['_GLOSSARYSERVICE']._serialized_start=329
  _globals['_GLOSSARYSERVICE']._serialized_end=513
# @@protoc_insertion_point(module_scope)
